version: "3.8"

services:
  api:
    image: ghcr.io/DVM-Software-Inc/backend-go-hello:latest
    container_name: backend-go-hello
    env_file:
      - .env
    networks:
      - proxy
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-go-hello.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.backend-go-hello.entrypoints=websecure"
      - "traefik.http.routers.backend-go-hello.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend-go-hello.loadbalancer.server.port=8080"

networks:
  proxy:
    external: true
