name: Go Backend CI/CD

on:
  push:
    branches: ["dev", "main"]

env:
  IS_PROD: ${{ github.ref_name == 'main' }}
  ENVIRONMENT: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}

jobs:
  build:
    name: Build & Push Image
    uses: DVM-Software-Inc/infra/.github/workflows/build.yml@main
    with:
      image_name: backend-go-template
      environment: ${{ env.ENVIRONMENT }}
    secrets: inherit

  deploy:
    name: Deploy to VPS
    needs: build
    if: github.ref_name == 'dev' || github.ref_name == 'main'
    uses: DVM-Software-Inc/infra/.github/workflows/deploy.yml@main
    with:
      compose_file: docker-compose.yml
      image_name: backend-go-template
      environment: ${{ env.ENVIRONMENT }}
    secrets: inherit
